matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode8

language: node_js

services:
  - docker

install:
  - npm install -g grunt-cli
  - npm install
  - pip install --user requests

script:
  - './build.sh && make -C server test'

after_success:
  - '[ -n "$TRAVIS_TAG" ] && server/upload_github_release.py'
